version: "3.3"
services:
  backend:
    image: todo-backend:1.0
    build: ./Backend
    env_file:
      - ./Backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #     delay: 5s
    #     max_attempts: 3
    #     window: 10s
  db:
    image: mongo:5.0.5
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./DB/.env
    # healthcheck:
    #   test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
volumes:
  mongodata:
    external: true
